# Extends the base docker-compose.yml file.
# Services with the same name will be merged.

version: "3.5"

services:
    proxy:
        build:
            args:
                - CONTAINER_NAME_UI
                - UI_PORT
            dockerfile: ./packages/proxy/310.dockerfile
        depends_on:
            - reference_ui
    geolocation:
        build:
            args:
                - GEO_PORT
            context: https://${COURSE_GH_ORG_TOKEN}@github.ubc.ca/cpsc310/cpsc310geocoder.git
        container_name: ${CONTAINER_NAME_GEO}
        ports:
            - ${GEO_PORT}:${GEO_PORT}
        restart: always
        user: "${UID}"
    reference_ui:
        build:
            args:
                - UI_PORT
                - UID
            context: https://${COURSE_GH_ORG_TOKEN}@github.ubc.ca/cpsc310/project-oracle.git
            dockerfile: ui.dockerfile
        container_name: ${CONTAINER_NAME_UI}
        expose:
            - ${UI_PORT}
        restart: always
        user: "${UID}"

