version: "3"
services:
    container-host:
        build: host/
        image: cntr
        env_file: host/.env
        networks:
            default:
            grade:
                ipv4_address: 172.28.2.0
        ports:
            - "3000:3000"
            - "7777:7777"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        cap_add:
            - NET_ADMIN
        privileged: true
networks:
    grade:
        driver: bridge
        driver_opts:
            ip-range: "172.28.5.0/24"
            gateway: "172.28.5.254"
        ipam:
            config:
                - subnet: "172.28.0.0/16"

#             --driver=bridge \
# --subnet=172.28.0.0/16 \
# --ip-range=172.28.5.0/24 \
# --gateway=172.28.5.254 \
