# Extends the base docker-compose.yml file.
# Services with the same name will be merged.

version: "3.5"

services:
    proxy:
        build:
            args:
                - CONTAINER_NAME_GEO
                - CONTAINER_NAME_UI
                - GEO_PORT
                - UI_PORT
            dockerfile: 310.dockerfile
        depends_on:
            - reference_ui
            - geolocation
    portal:
        depends_on:
            - autotest
    autotest:
        build:
            args:
                - PORT=${AUTOTEST_PORT}
            context: packages/autotest
        container_name: ${CONTAINER_NAME_AUTOTEST}
        depends_on:
            - base
            - db
            - grader
        env_file: .env
        expose:
            - ${AUTOTEST_PORT}
        restart: always
        user: "${UID}"
    grader:
        build:
            args:
                - PORT=${GRADER_PORT}
            context: packages/grader
        container_name: ${CONTAINER_NAME_GRADER}
        # DO NOT PASS THE ENTIRE ENVIRONMENT FILE
        # Students could log the token values
        environment:
            - GH_BOT_TOKEN  # Only access student repos not oracle
            - UID
            - GRADER_HOST_DIR
            - DOCKER_NET=grading_net
            - HOSTS_ALLOW
        expose:
            - ${GRADER_PORT}
        networks:
            default:
            grader:
                ipv4_address: 172.28.2.0
        restart: always
        user: "0"  # Run as root; needs permission to interact with docker service
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "${GRADER_HOST_DIR}:${GRADER_PERSIST_DIR}"
        privileged: true
    geolocation:
        build:
            args:
                - GEO_PORT
            context: https://${COURSE_GH_ORG_TOKEN}@github.ubc.ca/cpsc310/cpsc310geocoder.git
        container_name: ${CONTAINER_NAME_GEO}
        expose:
            - ${GEO_PORT}
        restart: always
        user: "${UID}"
    reference_ui:
        build:
            args:
                - UI_PORT
            context: https://${COURSE_GH_ORG_TOKEN}@github.ubc.ca/cpsc310/project_oracle.git#frontend-prod
            dockerfile: ui.dockerfile
        container_name: ${CONTAINER_NAME_UI}
        expose:
            - ${UI_PORT}
        restart: always
        user: "${UID}"

# Run grading containers in a subnet to make it easy to block all traffic using iptables.
networks:
    grader:
        driver: bridge
        driver_opts:
            ip-range: "172.28.5.0/24"
            gateway: "172.28.5.254"
        ipam:
            config:
                - subnet: "172.28.0.0/16"
        name: ${GRADE_NET_NAME}
