version: "3"

services:
    db:
        image: mongo:3-jessie
        volumes:
            - ./data/db:/data/db
    geolocation:
        build: https://${GH_CPSC310TOKEN}@github.ubc.ca/cpsc310/cpsc310geocoder.git
        ports:
            - "11316:11316" # this is the geolocation port for d2/d3; exposd globally
    # reference-ui:
    #     build: https://${TOKEN}:@github.company.com/org/repo.git
    #     ports:
    #         - "11315:11315" # this is the reference UI for all deliverables; exposd globally
    # portal-backend:
    #     build: https://${UBCCPSCTOKEN}github.com/ubccpsc/sdmm-portal-backend.git
    #     ports:
    #         - "5000:5000" # this is the reference UI for all deliverables; exposd globally
    portal-frontend:
        build: https://github.com/ubccpsc/sdmm-portal.git
        env_file: "../sdmm-portal/.env"
        # depends_on:
        #     - portalBackend
        ports:
            - "443:443" # exposed globally
        volumes:
            - "../sdmm-portal/ssl:/app/ssl"
    core:
        build: core/
        depends_on:
            - db
            - grader
        ports:
            - "11333:11333" # this is the github webhook port; exposed globally
    grader:
        build: grader/
        environment:
            - "HOST_DIR=/home/cs310/autotest/data/runs"
            - "HOST_NAME=172.28.2.0"
            - "SOCK_PORT=7777"
            - "USER_UID=1008"
            - "DOCKER_NET=autotest_grader"
            - "GITHUB_TOKEN=${GH_CPSC310TOKEN}"
        networks:
            default:
            grader:
                ipv4_address: 172.28.2.0
        ports:
            - "3000:3000" # REST endpoint for grader; not exposed globally
            - "7777:7777" # Socket endpoint for grader; not exposed globally
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "/home/cs310/autotest/data/runs:/data"
        cap_add:
            - NET_ADMIN
        privileged: true

networks:
    grader:
        driver: bridge
        driver_opts:
            ip-range: "172.28.5.0/24"
            gateway: "172.28.5.254"
        ipam:
            config:
                - subnet: "172.28.0.0/16"
