version: "3"

services:
    proxy:
        build:
            args:
                - SSL_CERT_PATH
                - SSL_KEY_PATH
                - BACKEND_PORT
            context: packages/router
        container_name: proxy
        depends_on:
            - portal
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "${HOST_SSL_CERT_PATH}:${SSL_CERT_PATH}"
            - "${HOST_SSL_KEY_PATH}:${SSL_KEY_PATH}"
    portal:
        build:
            args:
                - GH_BOT_USERNAME
                - GH_BOT_EMAIL
                - PORT=${BACKEND_PORT}
            context: packages/portal
        container_name: portal
        depends_on:
            - db
        env_file: .env
        expose:
            - ${BACKEND_PORT}
        volumes:
            - "${HOST_SSL_CERT_PATH}:${SSL_CERT_PATH}"
            - "${HOST_SSL_KEY_PATH}:${SSL_KEY_PATH}"
    db:
        container_name: db
        expose:
            - "27017"
        image: mongo:3-jessie
        volumes:
            - ./data/db:/data/db
