# Extends the base docker-compose.yml file.
# Services with the same name will be merged.

version: "3.5"

services:
    proxy:
        build:
            args:
                - CONTAINER_NAME_UI
                - UI_PORT
            dockerfile: ./packages/proxy/310.dockerfile
        depends_on:
            - reference_ui
    geolocation:
        build:
            args:
                - GEO_PORT
            context: https://${COURSE_GH_ORG_TOKEN}@github.ubc.ca/cpsc310/cpsc310geocoder.git
        container_name: ${CONTAINER_NAME_GEO}
        ports:
            - ${GEO_PORT}:${GEO_PORT}
        restart: always
        user: "${UID}"
    reference_ui:
        build:
            args:
                - UI_PORT
                - UID
            context: https://${COURSE_GH_ORG_TOKEN}@github.ubc.ca/cpsc310/project_oracle_sdmm.git
            dockerfile: ui.dockerfile
        container_name: ${CONTAINER_NAME_UI}
        expose:
            - ${UI_PORT}
        restart: always
        user: "${UID}"
    patchtool:
        image: "sinatra"
        build:
            context: https://${COURSE_GH_ORG_TOKEN}@github.ubc.ca/cpsc310/repoPatchTool.git#webservice
#        ports:
#        - "127.0.0.1:${PATCH_TOOL_PORT}:3000" #If you remove this you disallow any outside access
        volumes:
        - "${HOST_SSL_CERT_PATH}:/usr/cert.pem"
        - "${HOST_SSL_KEY_PATH}:/usr/key.pem"
        container_name: patchtool
        environment:
        - GH_BOT_TOKEN
        - COURSE_GH_ORG_TOKEN
        - PATCH_SOURCE_REPO

