# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0
      - image: circleci/mongo:3.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --ignore-engines

      - run:
            command: cd packages/common && yarn install --ignore-engines
            name: Preparing common

      - run:
            command: cd packages/autotest && yarn install --ignore-engines
            name: Preparing autotest

      - run:
            command: cd packages/portal/backend && mkdir -p ssl/ && yarn install --ignore-engines
            name: Preparing backend

      - save_cache:
          paths:
            - node_modules
#            - packages/common/node_modules
#            - packages/portal-backend/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Setup encrypted .env variable per Classy fork (chooses default env.enc when not set)"
          command: |
            echo 'export ENV_ENC_FILE="${ENCRYPT_ENV:-env}"' >> $BASH_ENV # Redirect ENCRYPT_ENV into $BASH_ENV

     # openssl aes-256-cbc -e -md sha512 -in ../.env -out .config -k $KEY
      - run:
            command: cd .circleci && openssl aes-256-cbc -d -md sha512 -in "$ENV_ENC_FILE.enc" -out ../.env -k $ENVKEY
            name: Configuring .env
            when: always

      - run:
            command: cd .circleci && mkdir -p ../packages/portal-backend/ssl && openssl aes-256-cbc -d -md sha512 -in fullchain.enc -out ../packages/portal/backend/ssl/fullchain.pem -k $ENVKEY
            name: Configuring SSL-1
            when: always

      - run:
            command: cd .circleci && openssl aes-256-cbc -d -md sha512 -in privkey.enc -out ../packages/portal/backend/ssl/privkey.pem -k $ENVKEY
            name: Configuring SSL-2
            when: always

      - run:
            command: cd packages/common && ../../node_modules/typescript/bin/tsc
            name: Building common
            when: always

      - run:
            command: cd packages/portal/backend && ../../../node_modules/typescript/bin/tsc
            name: Building backend
            when: always

      - run:
            command: cd packages/portal/frontend && ../../../node_modules/typescript/bin/tsc && yarn webpack
            name: Building frontend and bundle with Webpack
            when: always

      # statically validate the frontend (this is the best we can do as there are no automated UI tests yet)
#      - run:
#            command: cd packages/portal/frontend && ../../../node_modules/typescript/bin/tsc && ../../../node_modules/webpack/bin/webpack.js
#            name: Building frontend
#            when: always

      - run:
            command: cd packages/autotest && ../../node_modules/typescript/bin/tsc
            name: Building autotest
            when: always

      - run:
            command: yarn run lint
            name: Linting project
            when: always

      - run:
            command: git config --global user.email "CI@test.com" && git config --global user.name "CI Test Name"
            name: Configure local git
            when: on_success

      - run:
            command: |
                      set -e
                      cd packages/portal/backend
                      yarn coverCI
            name: Running backend tests
            environment:
              MOCHA_FILE: testOutput/backend/test/test-results.xml
            when: on_success

      - run:
            command: mkdir -p testOutput/backend/test/ && ./node_modules/junit-viewer/bin/junit-viewer --results=packages/portal/backend/testOutput/backend/test/test-results.xml --save=testOutput/backend/test/index.html
            name: Converting backend test results to HTML
            when: on_success

      - run:
            command: |
                      set -e
                      cd packages/autotest
                      yarn coverCI
            name: Running autotest tests
            environment:
              MOCHA_FILE: testOutput/autotest/test/test-results.xml
            when: on_success

      - run:
            command: mkdir -p testOutput/autotest/test/ && ./node_modules/junit-viewer/bin/junit-viewer --results=packages/autotest/testOutput/autotest/test/test-results.xml --save=testOutput/autotest/test/index.html
            name: Converting autotest test results to HTML
            when: on_success

      - run:
            command: cd packages/portal/backend && yarn coveralls
            name: Running backend coveralls
            when: on_success
# coveralls doesn't integrate coverage
# so this overwrites the backend coverage (which we care about more)
# this is disabled and shouldn't be enabled until this is fixed
#      - run:
#            command: cd packages/autotest && yarn coveralls
#            name: Running autotest coveralls
#            when: always

      - run:
            command: cd packages/portal/backend && yarn codecov
            name: Running backend codecov
            when: on_success

      - store_test_results:
          path: testOutput

      - store_artifacts:
          path: testOutput

      - run:
            command: rm .env && rm packages/portal/backend/ssl/fullchain.pem && rm packages/portal/backend/ssl/privkey.pem
            name: Cleaning up
            when: always

  build_run_stop:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project

    environment:
      TEST_RESULTS: /tmp/test-logs

    steps:
      - checkout

      - run:
          name: "Setup encrypted .env variable per Classy fork (chooses default env.enc when not set)"
          command: |
            set -x
            echo 'export ENV_ENC_FILE="${ENCRYPT_ENV:-env}"' >> $BASH_ENV # Redirect ENCRYPT_ENV into $BASH_ENV

     # openssl aes-256-cbc -e -md sha512 -in ../.env -out .config -k $KEY
      - run:
          name: Configuring .env
          command: cd .circleci && openssl aes-256-cbc -d -md sha512 -in "$ENV_ENC_FILE.enc" -out ../.env -k $ENVKEY
          when: always

     # CircleCI runs in root, which is 0 for UID & GID. Must do after file unencrypted.
      - run:
          name: "Export UID and GID to configuration file"
          command: |
            set -x
            echo -e "GID=0\nUID=0\n" >> .env

     # SSLs need to be set for Portal container or else "volume name is too short" Docker Portal create error
      - run:
          name: "Export SSL CERT and SSL KEY paths"
          command: |
            set -x
            SSL_PATH="${HOME}/project/packages/portal/backend/ssl"
            echo -e "HOST_SSL_CERT_PATH=$SSL_PATH/fullchain.pem\nHOST_SSL_KEY_PATH=$SSL_PATH/privkey.pem\n" >> .env

      - run:
          name: Generate self-signed certs
          command: |
            set -x
            SSL_PATH="${HOME}/project/packages/portal/backend/ssl"
            mkdir -p $SSL_PATH && openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout $SSL_PATH/privkey.pem -out $SSL_PATH/fullchain.pem -subj "/C=GB/ST=Vancouver/L=Vancouver/O=Global Security/OU=IT Department/CN=test.com"
          when: always

      - run:
          name: Create mount path for MongoDB
          command: |
            set -x
            sudo mkdir -p /var/opt/classy/db

      - run:
          name: Create paths for artifact collections
          command: |
            set -x
            sudo mkdir -p /tmp/test-logs/ && sudo chmod 777 -R /tmp/test-logs && touch /tmp/test-logs/stdout
            sudo mkdir -p /tmp/test-results/ && sudo chmod 777 -R /tmp/test-results && touch /tmp/test-results/stdout

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d 2>&1 | tee -a /tmp/test-logs/stdout

      # curl -k command turns of SSL cert verification. These are self-signed certs and we just want to know the app is running
      - run:
          name: curl command to test Portal front-end (expect a bunch of onsen UI html)
          command: curl -k https://localhost 2>&1 | tee -a /tmp/test-results/curl-output

      - run:
          name: curl command to test Portal back-end (expect 'success', org - 'classytest', name - classytest')
          command: curl -k https://localhost/portal/config 2>&1 | tee -a /tmp/test-results/curl-output

      - run:
          name: curl command to test AutoTest back-end (expect 'Invalid AutoTest Secret - undefined')
          command: curl -k https://localhost/portal/at 2>&1 | tee -a /tmp/test-results/curl-output

      - run:
          name: Shut down containers
          command: docker-compose down 2>&1 | tee -a /tmp/test-logs/stdout

      - run:
          name: Cleaning up
          command: rm .env && rm ${HOME}/project/packages/portal/backend/ssl/fullchain.pem && rm ${HOME}/project/packages/portal/backend/ssl/privkey.pem && docker system prune -af 2>&1 | tee -a /tmp/test-logs/stdout
          when: always

      - store_artifacts:
          path: /tmp/test-logs
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  docker_compose_tests:
    jobs:
    #   - build
      - build_run_stop
  nightly:
    triggers:
      - schedule:
          # 5am PST time in UTC
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - feature/circle-ci-24-hour-build-test
    jobs:
      - build_run_stop
